######################## default configuration ####################
baseURL = "alborzdelft.nl"
title = "Alborz Association"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[params]
mainSections = ["events"]

[services]
  [services.disqus]
  # disqus short name
    shortname = ''