############################# English ############################
[en]
languageName = "En"
title = "Alborz Association"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Association"
footer_menu_middle = "Activities & Mentoring"
footer_menu_right = "Contact"
footer_content = "Delft Iranian Student Association"
# copyright
copyright = "© 2024 | D.I.S.A. Alborz | All rights reserved"
