# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Association"
identifier = "association"
weight = 2

[[main]]
name = "History"
parent = "association"
url = "history/"
weight = 1

[[main]]
name = "Statutes"
parent = "association"
url = "https://drive.google.com/file/d/1CE5unoZKy-xC0PnOIHDvCGLPxkmRNVCP/view?usp=sharing"
weight = 2

[[main]]
name = "Bylaws"
parent = "association"
url = "https://drive.google.com/file/d/12Qr3D_vwmDXxdByfGlcI7HewQZNg3leb/view?usp=sharing"
weight = 3

[[main]]
name = "Policy"
identifier = "policy"
parent = "association"
weight = 4

[[main]]
name = "2023-2024"
parent = "policy"
url = "https://drive.google.com/file/d/1avUxVeSgiNZQ5oEX9wnPKBGwj2asaRWh/view?usp=sharing"
weight = 1

[[main]]
name = "2022-2023"
parent = "policy"
url = "https://drive.google.com/file/d/16UE9rlulg0Amdmg_xEBRX72wtPNFlikP/view?usp=sharing"
weight = 2


[[main]]
name = "FAQ"
parent = "association"
url = "faq/"
weight = 5

[[main]]
name = "Boards"
identifier = "boards"
weight = 2

[[main]]
name = "Current Board"
parent = "boards"
url = "boards/board/"
weight = 1

[[main]]
name = "Former Boards"
parent = "boards"
url = "boards/former-boards/"
weight = 2

[[main]]
name = "Events"
identifier = "events"
url = "events/"
weight = 3

[[main]]
name = "Upcoming Events"
parent = "events"
url = "events/"
weight = 1

[[main]]
name = "Calendar"
parent = "events"
url = "calendar/"
weight = 2

[[main]]
name = "Support"
identifier = "support"
weight = 4

[[main]]
name = "Arrival in Delft"
parent = "support"
url = "support/arrival-in-delft/"
weight = 1

[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu left
[[footer_left]]
name = "Boards"
url = "board/"


# footer menu middle
[[footer_left]]
name = "Events"
url = "events"

[[footer_left]]
name = "Calendar"
url = "calendar/"

# footer menu right
#[[footer_middle]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#
#[[footer_middle]]
#name = "Terms & Conditions"
#url = "terms-conditions/"

[[footer_middle]]
name = "FAQ"
url = "faq/"

[[footer_right]]
name = "Email: alborzdelft@gmail.com"

[[footer_right]]
name = "Kanaalweg 4, 2628 EB Delft"