#################### default parameters ################################
logo = "images/logo.png"
logo_width = "100px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "D.I.S.A. Alborz association"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "https://formspree.io/f/xyyawegj" # contact form works with https://formspree.io

Copyright = "© 2024 | D.I.S.A. Alborz | All rights reserved"

# Type of pages to be rendered with a events view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Become a member"
link = "https://form.jotform.com/230291977411356"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/alborzdelft/"

[[social]]
title = "telegram"
icon = "fab fa-telegram" # themify icon : https://themify.me/themify-icons
link = "https://t.me/Alborzdelft"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/alborzdelft"