############################# English ############################
[en]
languageName = "En"
title = "Alborz Association"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "About us"
footer_menu_middle = "Events"
footer_menu_right = "Support"
footer_content = "Delft Iranian Student Association"
# copyright
copyright = "Alborz Association"
