# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Events"
url = "events/"
weight = 2

[[main]]
name = "Board"
url = "members/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

[[main]]
name = "FAQ"
url = "faq/"
weight = 5

# footer menu left
[[footer_left]]
name = "Board"
url = "members/"


# footer menu middle
[[footer_left]]
name = "Events"
url = "events"

# footer menu right
#[[footer_middle]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#
#[[footer_middle]]
#name = "Terms & Conditions"
#url = "terms-conditions/"

[[footer_middle]]
name = "FAQ"
url = "faq/"

[[footer_right]]
name = "Email: alborzdelft@gmail.com"

[[footer_right]]
name = "Kanaalweg 4, 2628 EB Delft"