[[footer_left]]
name = "About Us"
url = "#"
[[footer_left]]
name = "Events"
url = "events/"
[[footer_middle]]
name = "Members"
url = "members/"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"
[[footer_right]]
name = "FAQ"
url = "faq/"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Events"
url = "blog/"
weight = 2
[[main]]
name = "Members"
url = "pricing/"
weight = 3
[[main]]
name = "Contact"
url = "contact/"
weight = 4
[[main]]
name = "FAQ"
url = "faq/"
weight = 5
